import Page from "./components/page"

export default function index() {
	return (
		<Page>
			<div className="test">
				<a href=""> Пример 1 </a>
				<a href=""> Пример два </a>
				<a href=""> Пример три </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример 1 </a>
				<a href=""> Пример два </a>
				<a href=""> Пример три </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример 1 </a>
				<a href=""> Пример два </a>
				<a href=""> Пример три </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример 1 </a>
				<a href=""> Пример два </a>
				<a href=""> Пример три </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример 1 </a>
				<a href=""> Пример два </a>
				<a href=""> Пример три </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
				<a href=""> Пример </a>
			</div>
		</Page>
	)
}